---
title: "mississippi-flux-calcs"
author: "Kate Morkeski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(ggplot2)
library(here)

```

# Read in fugacity data generated with pCO2sys

```{r}

may_fug <- read_csv("MAY_Working.csv")

may_fug[may_fug=="-999"]<-NA
may_fug[may_fug=="NaN"]<-NA

may_fug$date_time_utc <- as.POSIXct(may_fug$date_time_utc, tz = "UTC", format="%m/%d/%Y %H:%M")

# remove duplicate columns
may_fug <- may_fug %>% 
    select(-"YDay Calc", -"Cruise Day") %>%
    rename(dfCO2wa = "dfCO2(w-a)")

colnames(may_fug) <- gsub(" ", "_", colnames(may_fug))
  
```
# Read in wind data

```{r}

# wind speed from csv generated in mississippi-data-assembly.Rmd
GO_May_wind <- read_csv("GO_May_wind_interp.csv")
GO_May_wind <- rename(GO_May_wind, date_time_wind = date_time_utc)

# bind with GO data
may_fug <- cbind(may_fug, GO_May_wind)

may_fug$time_diff = may_fug$date_time_utc - may_fug$date_time_wind
# difference is < 60 s due to loss of seconds in date_time_utc

# remove duplicate columns
may_fug <- may_fug %>% 
    select(-date_time_utc) %>% 
    rename(date_time_utc = date_time_wind)

```

# Remove overnight records

```{r}

#Based on GO log sheets, boat was docked 10-11 May 18:50-4:35 local, which is 23:50-09:35 UTC and 1652226540 to 1652261755 numeric
may_fug$date_time_num <- as.numeric(may_fug$date_time_utc)

may_fug <- may_fug %>% relocate(date_time_num, .before = wind_m_s_MSY)

may_fug <- may_fug %>%
  mutate(leg = case_when(1652226540 < date_time_num & date_time_num < 1652261755 ~ "dock"))

may_fug <- may_fug %>%
  filter(is.na(leg)) 

may_fug <- may_fug %>% select(-time_diff, -leg)

```
# Calculate U_10

```{r}

# MSY elevation is 9 m
# DSF elevation is 0 m

# use wind speed to calculate U_10 based on Large and Pond (1981) as reprinted in Yu et al 2020
may_fug$U_10_MSY = may_fug$wind_m_s_MSY / (1 + (sqrt(0.0011)/0.4) * log(9/10))
may_fug$U_10_rig_0m = may_fug$wind_m_s_rig / (1 + (sqrt(0.0011)/0.4) * log(0/10))
may_fug$U_10_rig_1m = may_fug$wind_m_s_rig / (1 + (sqrt(0.0011)/0.4) * log(1/10))
may_fug$U_10_rig_10m = may_fug$wind_m_s_rig / (1 + (sqrt(0.0011)/0.4) * log(10/10))

# according to data source https://mesonet.agron.iastate.edu/request/download.phtml?network=LA_ASOS, 
# height of DSF data is 0 m. Can't calculate U_10 with height of 0 and seems unlikely anyway
# plugging in alternate heights to calculate effect on U_10

# plot wind speed
ggplot(may_fug, aes(x = date_time_utc, y = wind_m_s_MSY, color = "MSY")) +
  labs(x = "datetime", y = "U10") +
  geom_point() + 
  geom_point(data = may_fug, aes(x = date_time_utc, y = wind_m_s_rig, color = "rig")) +
  labs(x = "datetime", y = "wind speed m/s") +
    theme_minimal()

# plot U_10
ggplot(may_fug, aes(x = date_time_utc, y = U_10_rig_0m, color = "0m")) +
  labs(x = "datetime", y = "U10") +
  geom_point() + 
  theme_minimal()

# plot U_10
ggplot(may_fug, aes(x = date_time_utc, y = U_10_rig_1m, color = "1m")) +
  labs(x = "datetime", y = "U10") +
  geom_point() + 
  geom_point(data = may_fug, aes(x = date_time_utc, y = U_10_rig_10m, color = "10m")) +
  labs(x = "datetime", y = "U10") +
    theme_minimal()

# plot U_10
ggplot(may_fug, aes(x = date_time_utc, y = U_10_MSY, color = "MSY")) +
  labs(x = "datetime", y = "U10") +
  geom_point() + 
    theme_minimal()

```


# Add gas transfer velocity, solubility, and flux

```{r}

temp_C = may_fug$temperature
sal = may_fug$CTDSAL_PSS78


# as check: calculate #Schmidt number for seawater (35 ppt) at 20 C
Sc = 2116.8 + (-136.25*20) + (4.7353*20^2) + (-0.092307*20^3) + (0.0007555*20^4)
# Schmidt number for freshwater
Sc_fresh = 1923.6 + (-125.06*20) + (4.3773*20^2) + (-0.085681*20^3) + (0.00070284*20^4)

# calculate seawater Schmidt number at measured temp
may_fug$Sc_35ppt = 2116.8 + (-136.25*temp_C) + (4.7353*temp_C^2) + (-0.092307*temp_C^3) + (0.0007555*temp_C^4)
# calculate freshwater  Schmidt number at measured temp
may_fug$Sc_fresh = 1923.6 + (-125.06*temp_C) + (4.3773*temp_C^2) + (-0.085681*temp_C^3) + (0.00070284*temp_C^4)

# calculate gas transfer velocity, k, in cm per hr
# use U_10 only from MSY for now
may_fug$k_cm_hr_35ppt = 0.251*may_fug$U_10_MSY*((may_fug$Sc_35ppt/660)^-0.5)
may_fug$k_cm_hr_fresh = 0.251*may_fug$U_10_MSY*((may_fug$Sc_fresh/660)^-0.5)

hist(may_fug$k_cm_hr_35ppt)
hist(may_fug$k_cm_hr_fresh)

# coefficents for Henry's law coefficient for CO2 from Weiss 1974 as reported in Emerson & Hedges with units mol kg-1 atm-1
# A1 = -60.2409 
# A2 = 93.4517 
# A3 = 23.3585 
# B1 = 0.023517 
# B2 = -0.023656 
# B3 = 0.0047035 

# coefficents for K_sub_0 from Weiss 1974 in units mol L-1 atm-1
# K' for CO2 from Weiss 1974 as reported in Wanninkhof 2014 with units mol L-1 atm-1
A1 = -58.0931
A2 = 90.5069
A3 = 22.2940
B1 = 0.027766 
B2 = -0.025888
B3 = 0.0050578 

# calculate Henry's law coefficient
may_fug$Kh_mol_kg_atm = exp(A1+A2*(100/(273.15+temp_C)) + A3*log((273.15+temp_C)/100) +sal*(B1+B2*((273.15+temp_C)/100)+B3*((273.15+temp_C)/100)^2))

hist(may_fug$Kh_mol_kg_atm)

may_fug$K_mol_L_atm = exp(A1+A2*(100/(273.15+temp_C)) + A3*log((273.15+temp_C)/100) +sal*(B1+B2*((273.15+temp_C)/100)+B3*((273.15+temp_C)/100)^2))

hist(may_fug$K_mol_L_atm)

# need K' for water saturated gas?
# need P_H20
#may_fug$K_prime = may_fug$Kh_mol_kg * may_fug$dfCO2wa / may_fug$xCO2_dry (may_fug$Patm - P_H20)

# check to make sure Kh is calculated correctly. Should be 0.0324
#Kh = exp(A1+A2*(100/(273.15+20)) + A3*log((273.15+20)/100) +35*(B1+B2*((273.15+20)/100)+B3*((273.15+20)/100)^2))

# R syntax for natural log and e
#exp(0.5) # e^(1/2)
#log(1)  # natural logarithm

# Wanninkhof 2014 eq. 6 for simplified flux, F, in units mol per m2 per y
may_fug$F_direct_micromol_m2_y <- 7.7*10^-4 * may_fug$U_10_MSY * may_fug$dfCO2wa
may_fug$F_direct_micromol_m2_s <- 7.7*10^-4 * may_fug$U_10_MSY * may_fug$dfCO2wa*(1/365)*(1/24)*(1/3600)

# calculate Flux
may_fug$F_mol_m2_s_35ppt <- may_fug$k_cm_hr_35ppt * may_fug$K_mol_L_atm * may_fug$dfCO2wa* (1/100)*(1/3600)*(1000)*(1/10^6)
may_fug$F_micromol_m2_d_35ppt <- may_fug$k_cm_hr_35ppt * may_fug$K_mol_L_atm * may_fug$dfCO2wa* (24/100)*(1000)
may_fug$F_mmol_m2_d_35ppt <- may_fug$k_cm_hr_35ppt * may_fug$K_mol_L_atm * may_fug$dfCO2wa* (24/100)*(1000)*(1/1000)
may_fug$F_micromol_m2_s_35ppt <- may_fug$k_cm_hr_35ppt * may_fug$K_mol_L_atm * may_fug$dfCO2wa* (1/100)*(1/3600)*(1000)

ggplot(may_fug, aes(x = date_time_utc, y = F_mol_m2_s_35ppt)) +  geom_point() +  theme_minimal()
ggplot(may_fug, aes(x = date_time_utc, y = F_micromol_m2_d_35ppt)) +  geom_point() +  theme_minimal()
ggplot(may_fug, aes(x = date_time_utc, y = F_mmol_m2_d_35ppt)) +  geom_point() +  theme_minimal()
ggplot(may_fug, aes(x = date_time_utc, y = F_micromol_m2_s_35ppt)) +  geom_point() +  theme_minimal()

# calculate Flux 
# formula from Congo data sheet. need to check units
# may_fug$F_mM_m2_d_35ppt <- may_fug$k_cm_hr_35ppt * may_fug$Kh_mol_kg_atm * may_fug$dfCO2wa* 24 * 1 *0.01
# may_fug$F_mM_m2_d_fresh <- may_fug$k_cm_hr_fresh * may_fug$Kh_mol_kg_atm * may_fug$dfCO2wa* 24 * 1 *0.01
# may_fug$F_diff <- may_fug$F_mM_m2_d_35ppt - may_fug$F_mM_m2_d_fresh
#

```

# Add cruise leg label
```{r}
# mapping <- mapping %>%
#   mutate(leg = case_when(station <10 ~ "river",
#                          station == 10 ~ "gulf",
#                          station > 14 ~ "gulf",
#                          TRUE ~ "spur"))

may_fug <- may_fug %>%
  mutate(leg = case_when(CTDSAL_PSS78 <2.5 ~ "fresh",
                         CTDSAL_PSS78 > 2.5 & CTDSAL_PSS78 <34 ~ "plume",
                         CTDSAL_PSS78 > 34 ~ "gulf",
                         TRUE ~ "transit"))
```


# Plot by date time

```{r}

ggplot(may_fug, aes(x = date_time_utc, y = temperature)) +
  geom_point() +
  labs(x = "date_time_utc", y = "Temperature", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = CTDSAL_PSS78)) +
  geom_point() +
  labs(x = "date_time_utc", y = "Salinity CTD", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = Patm)) +
  geom_point() +
  labs(x = "date_time_utc", y = "Atmospheric pressure mbar", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = xCO2_dry, color = leg)) +
  geom_point() +
  labs(x = "date_time_utc", y = "XCO2_dry", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = dfCO2wa)) +
  geom_point() +
  labs(x = "date_time_utc", y = "dfCO2", color = "") +
  theme_minimal()

# ggplot(may_fug, aes(x = date_time_utc, y = F_mM_m2_d_35ppt)) +
#   geom_point() +
#   labs(x = "Date Time UTC", y = "F_mM_m2_d", color = "") +
#   theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = F_direct_micromol_m2_y)) +
  geom_point() +
  labs(x = "Date Time UTC", y = "F_direct", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = date_time_utc, y = F_mol_m2_s_35ppt)) +
  geom_point() +
  labs(x = "Date Time UTC", y = "F_mol_m2_s", color = "") +
  theme_minimal()

```
# Plot by latitude

```{r}

ggplot(may_fug, aes(x = lat, y = temperature, color = leg)) +
  geom_point() +
  labs(x = "Latitude", y = "Temperature", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = lat, y = CTDSAL_PSS78, color =leg)) +
  geom_point() +
  labs(x = "Latitude", y = "Salinity CTD", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = lat, y = Patm, color = leg)) +
  geom_point() +
  labs(x = "Latitude", y = "Atmospheric pressure mbar", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = lat, y = xCO2_dry, color = leg)) +
  geom_point() +
  labs(x = "Latitude", y = "XCO2_dry", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = lat, y = dfCO2wa, color = leg)) +
  geom_point() +
  labs(x = "Latitude", y = "dfCO2", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = lat, y = F_mol_m2_s_35ppt, color = leg)) +
  geom_point() +
  labs(x = "Latitude", y = "F_mol_m2_s", color = "") +
  theme_minimal()

```
# Plot by salinity

```{r}

ggplot(may_fug, aes(x = CTDSAL_PSS78, y = temperature, color = leg)) +
  geom_point() +
  labs(x = "Salinity CTD", y = "Temperature", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = CTDSAL_PSS78, y = Patm, color = leg)) +
  geom_point() +
  labs(x = "Salinity CTD", y = "Atmospheric pressure mbar", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = CTDSAL_PSS78, y = xCO2_dry, color = leg)) +
  geom_point() +
  labs(x = "Salinity CTD", y = "XCO2_dry", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = CTDSAL_PSS78, y = dfCO2wa, color = leg)) +
  geom_point() +
  labs(x = "Salinity CTD", y = "dfCO2", color = "") +
  theme_minimal()

ggplot(may_fug, aes(x = CTDSAL_PSS78, y = F_mol_m2_s_35ppt, color = leg)) +
  geom_point() +
  labs(x = "Salinity CTD", y = "F_mol_m2_s", color = "") +
  theme_minimal()

```
# write summary file

```{r}

may_summary <- may_fug %>%
  select(date_time_utc, lat, long, Patm, temperature, Tin_interp, CTDSAL_PSS78, leg, Type, xCO2_dry, Std_Offset, xCO2_corr, xCO2_interp_corr, xCO2A_Corrected, fCO2_water, fCO2_interp, dfCO2wa, U_10_MSY, Sc_35ppt, k_cm_hr_35ppt, K_mol_L_atm, F_mol_m2_s_35ppt, F_mmol_m2_d_35ppt, F_micromol_m2_s_35ppt)

may_summary <- may_summary %>%
  rename(Latitude = lat, 
         Longitude = long, 
         Patm_mbar = Patm,
         Temperature_raw_C = temperature,
         Temperature_adj_C = Tin_interp,
         xCO2_dry_ppm = xCO2_dry, 
         Std_Offset_ppm = Std_Offset, 
         xCO2_EQU_corr_ppm = xCO2_corr, 
         xCO2_ATM_interp_ppm = xCO2_interp_corr, 
         xCO2_ATM_ppm = xCO2A_Corrected, 
         fCO2_water_microatm = fCO2_water, 
         fCO2_ATM_interp_microatm = fCO2_interp, 
         dfCO2_microatm = dfCO2wa, 
         U_10_MSY_m_s = U_10_MSY,
         F_mol_m2_s = F_mol_m2_s_35ppt,
         F_mmol_m2_d = F_mmol_m2_d_35ppt,
         F_micromol_m2_s = F_micromol_m2_s_35ppt)

write.csv(may_summary, here('Mississippi_CO2_flux_May.csv'), row.names = FALSE)

```


