---
title: "mississippi-CO2-summary"
author: "Kate Morkeski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(readr)
library(dplyr)
library(ggplot2)
library(geosphere)

library(sf)
library(pals)
library(RColorBrewer)

```

# Read in data from both cruises

```{r}

may <- read_csv("Mississippi_CO2_flux_May.csv")
oct <- read_csv("Mississippi_CO2_flux_Oct.csv")

may_EQU <- may %>% 
  filter(Type == "EQU" | Type == "EQU-DRAIN") %>% 
  filter(!is.na(Latitude))

oct_EQU <- oct %>% 
  filter(Type == "EQU" | Type == "EQU-DRAIN")


```


# Calculate cruise distance
```{r}

for (i in 1:nrow(may)) {
  start_lon <- may$Longitude[i]
  start_lat <- may$Latitude[i]
  may$inc_dist_km[i] <- as.numeric(NA)
  # add an if to skip the row if df lon and/or lat is NA
  if (!is.na(start_lon) & !is.na(start_lat)) {
  next_lon <- may$Longitude[i+1]
  next_lat <- may$Latitude[i+1]
  start_lon_lat <- c(start_lon,start_lat)
  next_lon_lat <- c(next_lon, next_lat)}
    may$inc_dist_km[i] <- distHaversine(start_lon_lat, next_lon_lat, r=6378.137)
     }

may$inc_dist_km[1:5] <- 0
may$cruise_dist_km <-  cumsum(may$inc_dist_km)

for (i in 1:nrow(oct)) {
  start_lon <- oct$Longitude[i]
  start_lat <- oct$Latitude[i]
  next_lon <- oct$Longitude[i+1]
  next_lat <- oct$Latitude[i+1]
  oct$inc_dist_km[i] <- as.numeric(NA)
  # add an if to skip the row if df lon and/or lat is NA
  if (!is.na(start_lon) & !is.na(start_lat)) {
    start_lon_lat <- c(start_lon,start_lat)
    next_lon_lat <- c(next_lon, next_lat)}
    oct$inc_dist_km[i] <- distHaversine(start_lon_lat, next_lon_lat, r=6378.137)
     }

oct$inc_dist_km[1:5] <- 0
oct$cruise_dist_km <-  cumsum(oct$inc_dist_km)
```

# Calculate cruise distance

```{r}

ggplot(may, aes(x = cruise_dist_km, y = fCO2_water_microatm, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = cruise_dist_km, y = fCO2_water_microatm, color = "Fall"), size = 1.2) +
  labs(x = "Cruise distance (km)", y = "CO2 fugacity (microatm)") +
  scale_color_manual(values = c("purple3", "yellow3"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12), legend.position = "top")+
  scale_y_continuous(limits = c(0, 3000))+ 
theme(panel.grid.minor = element_blank())
ggsave("fCO2 by distance.png")


ggplot(may, aes(x = cruise_dist_km, y = F_micromol_m2_s, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = cruise_dist_km, y = F_micromol_m2_s, color = "Fall"), size = 1.2) +
  labs(x = "Cruise distance (km)", y = "CO2 Flux (micromol/m^2/s)") +
  scale_color_manual(values = c("purple3", "yellow3"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12), legend.position = "top")+
  scale_y_continuous(limits = c(-0.1, 0.4))+ theme(panel.grid.minor = element_blank())
ggsave("flux by distance.png")

ggplot(may, aes(x = cruise_dist_km, y = CTDSAL_PSS78, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = cruise_dist_km, y = CTDSAL_PSS78, color = "Fall"), size = 1.2) +
  labs(x = "Cruise distance (km)", y = "Salinity (psu)") +
  scale_color_manual(values = c("purple3", "yellow2"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))

ggplot(may, aes(x = cruise_dist_km, y = Temperature_raw_C, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = cruise_dist_km, y = Temperature_raw_C, color = "Fall"), size = 1.2) +
  labs(x = "Cruise distance (km)", y = "Temperature (C)") +
  scale_color_manual(values = c("purple3", "yellow2"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_y_continuous(limits = c(20, 30))

```


## Plots

```{r}

ggplot(may, aes(x = Latitude, y = Temperature_raw_C, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = Temperature_raw_C, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Temperature (C)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))+
  scale_y_continuous(limits = c(20, 30))

ggplot(may, aes(x = Latitude, y = CTDSAL_PSS78, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = CTDSAL_PSS78, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Salinity (PSU)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may_EQU, aes(x = Latitude, y = Patm_mbar, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct_EQU, aes(x = Latitude, y = Patm_mbar, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Atmospheric pressure (mbar)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))
 
ggplot(may_EQU, aes(x = Latitude, y = xCO2_EQU_corr_ppm, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct_EQU, aes(x = Latitude, y = xCO2_EQU_corr_ppm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "xCO2 (micromol/mol)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = dfCO2_microatm, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = dfCO2_microatm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "fCO2water-air (microatm)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = U_10_MSY_m_s, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = U_10_MSY_m_s, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "U10 (m/s)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = Sc_35ppt, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = Sc_35ppt, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Schmidt number") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = k_cm_hr_35ppt, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = k_cm_hr_35ppt, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "k_cm_hr_35ppt") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = K_mol_L_atm, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = K_mol_L_atm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "K_mol_L_atm") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = F_micromol_m2_s, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct, aes(x = Latitude, y = F_micromol_m2_s, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "CO2 Flux (micromol/m^2/s)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))+
  scale_y_continuous(limits = c(-0.1, 0.4))


```
## Plots

```{r}

ggplot(may_EQU, aes(x = Latitude, y = xCO2_EQU_corr_ppm, color = "Spring")) +
  geom_line(size = 1.2) +
  geom_line(data = oct_EQU, aes(x = Latitude, y = xCO2_EQU_corr_ppm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Surface water xCO2 (micromol/mol)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = fCO2_water_microatm, color = "Spring")) +
  geom_line(size = 1.2) +
  geom_line(data = oct, aes(x = Latitude, y = fCO2_water_microatm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "Surface water fCO2 (microatm)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = dfCO2_microatm, color = "Spring")) +
  geom_line(size = 1.2) +
  geom_line(data = oct, aes(x = Latitude, y = dfCO2_microatm, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "fCO2water-air (microatm)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))

ggplot(may, aes(x = Latitude, y = F_micromol_m2_s, color = "Spring")) +
  geom_line(size = 1.2) +
  geom_line(data = oct, aes(x = Latitude, y = F_micromol_m2_s, color = "Fall"), size = 1.2) +
  labs(x = "Latitude", y = "CO2 Flux (micromol/m^2/s)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0.7), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(28.5, 30.0))+
  scale_y_continuous(limits = c(-0.1, 0.4))

```

# By salinity

```{r}

ggplot(may_EQU, aes(x = CTDSAL_PSS78, y = fCO2_water_microatm, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct_EQU, aes(x = CTDSAL_PSS78, y = fCO2_water_microatm, color = "Fall"), size = 1.2) +
  labs(x = "Salinity (psu)", y = "Surface water fCO2 (microatm)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(0, 40.0))+
  scale_y_continuous(limits = c(0, 3000))

ggplot(may_EQU, aes(x = CTDSAL_PSS78, y = F_micromol_m2_s, color = "Spring")) +
  geom_point(size = 1.2) +
  geom_point(data = oct_EQU, aes(x = CTDSAL_PSS78, y = F_micromol_m2_s, color = "Fall"), size = 1.2) +
  labs(x = "Salinity (psu)", y = "CO2 Flux (micromol/m^2/s)") +
  scale_color_manual(values = c("purple", "goldenrod1"), name = "Season", breaks = c("Spring", "Fall"))+
  theme_minimal()+
  theme(line = element_line(size = 0), axis.title = element_text(size = 12, face = "bold"), axis.text = element_text(size = 10), legend.title = element_text(size = 12, face = 2), legend.text = element_text(size = 12))+
  scale_x_continuous(limits = c(0, 40.0))+
  scale_y_continuous(limits = c(-0.1, 0.4))
  

```
# use GSHHS coastline data per Dylan's code

```{r}

# turn off spherical geometry to avoid "duplicate vertex" errors
sf_use_s2(FALSE)

# read shapefile from wherever the file is located
mass <- st_read(here("GSHHS_f_L1")) %>%
  st_make_valid() %>%
  st_crop(xmin = -90.5, xmax = -89.0, ymin = 27, ymax = 30)

# plot result
ggplot()+geom_sf(data = mass, fill = "darkgrey", colour = "black")+
  coord_sf(crs = 4326, xlim = c(-90.5, -89), ylim = c(27, 30))

# TODO: troubleshoot data and GSHHG coordinates appearing offset
# try turning data into a shapefile
may_SF <- st_as_sf(may_EQU,
                     coords = c("Longitude", "Latitude"),
                     crs = 4326)

# plot data with GSHHG map
ggplot()+geom_sf(data = mass, fill = "darkgrey", colour = "black")+
  coord_sf(xlim = c(-90.5, -89), ylim = c(28.5, 30))+
geom_sf(data = may_SF, aes(color = F_micromol_m2_s)) +  
  scale_fill_gradient2(low = "#06A5C7", mid = "#06A5C7", high = "#B40426", aesthetics = "color", midpoint = 0, limits = c(-0.1, 0.4)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```

```{r}

us_map <- map_data("state")

louisiana <- us_map %>% 
  filter(region %in% "louisiana") 

mouth <- louisiana %>% filter(long > -91.5 & lat < 30.5)

```

```{r}

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = may_EQU, aes(x = Longitude, y = Latitude, color = F_micromol_m2_s)) +  
  scale_fill_gradient2(low = "#06A5C7", mid = "#06A5C7", high = "#B40426", aesthetics = "color", midpoint = 0, limits = c(-0.1, 0.4)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("flux May.png")

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = oct_EQU, aes(x = Longitude, y = Latitude, color = F_micromol_m2_s)) +  
  scale_fill_gradient2(low = "#06A5C7", mid = "#06A5C7", high = "#B40426", aesthetics = "color", midpoint = 0, limits = c(-0.1, 0.4)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("flux Oct.png")
 
```


```{r}

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = may_EQU, aes(x = Longitude, y = Latitude, color = Temperature_raw_C)) +  
  scale_fill_gradientn(colors = c("#EFF3FF", "#C6DBEF", "#9ECAE1", "#6BAED6", "#4292C6", "#2171B5", "#084594"), aesthetics = "color", limits = c(20, 27.5))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("temp May.png")

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = oct_EQU, aes(x = Longitude, y = Latitude, color = Temperature_raw_C)) +  
  scale_fill_gradientn(colors = c("#EFF3FF", "#C6DBEF", "#9ECAE1", "#6BAED6", "#4292C6", "#2171B5", "#084594"), aesthetics = "color", limits = c(20, 27.5))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("temp Oct.png")

```
```{r}

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = may_EQU, aes(x = Longitude, y = Latitude, color = CTDSAL_PSS78)) +  
  scale_fill_gradientn(colors = c("#FFFFCC", "#FFEDA0", "#FED976", "#FEB24C", "#FD8D3C", "#FC4E2A", "#E31A1C", "#BD0026", "#800026"), aesthetics = "color", limits = c(0, 40))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("sal May.png")

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = oct_EQU, aes(x = Longitude, y = Latitude, color = CTDSAL_PSS78)) +  
  scale_fill_gradientn(colors = c("#FFFFCC", "#FFEDA0", "#FED976", "#FEB24C", "#FD8D3C", "#FC4E2A", "#E31A1C", "#BD0026", "#800026"), aesthetics = "color", limits = c(0, 40))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(28.5, 30.5))
ggsave("sal Oct.png")

```

