---
title: "mississippi-data-assembly"
author: "Kate Morkeski"
date: "`r Sys.Date()`"
output: html_document
---
## Setup

Libraries used

```{r}

library(here)
library(readxl)
#library(lubridate)
library(tidyverse)
#library(httr)

```

# Read in CTD and bottle data

```{r}
compiled <- read_excel(here('MSR_1_Compiled.xlsx')) 
#salinity <- read_excel(here('MSR_1_Salinity.xlsx'))
```

# Format date and time

```{r}

compiled <- compiled %>%
  rename(time_utc = "Time (UTC)") %>%
  rename(station = Station_ID) %>%
  rename(cast = Cast_number) %>%
  rename(niskin = Niskin_ID) %>%
  rename(lat = "Latitude [decimal degrees]") %>%
  rename(long = "Longitude [decimal degrees]") 


# combine date and time
compiled$Date <- as.character(compiled$Date) 
compiled$time_utc <- as.character(compiled$time_utc)
compiled$time_utc <- gsub("1899-12-31 ", "", compiled$time_utc)
compiled$date_time_utc <- paste(compiled$Date, compiled$time_utc)
compiled$date_time_utc <- as.POSIXct(compiled$date_time_utc, tz = "GMT", format="%Y-%m-%d %H:%M:%OS")

compiled <- compiled %>% relocate(date_time_utc, .before = station)

```

# Correct apparent error in Station 6 coordinate

```{r}

# cast 6, niskin 6 entered with lat/long identical to station 7 entries
compiled <- compiled %>% 
  mutate(lat = replace(lat, station == 6 & niskin == 6, 29.35218)) %>%
  mutate(long = replace(lat, station == 6 & niskin == 6, -89.46450))  
 

```

# Create map

```{r}

# very generic state boundary
# need more detailed map data
us_map <- map_data("state")

louisiana <- us_map %>% 
  filter(region %in% "louisiana") 

mouth <- louisiana %>% filter(long > -91.5 & lat < 30.5)

mapping <- compiled %>% 
  select(station, cast, niskin, lat, long, CTDSAL_PSS78) 
  
ggplot(louisiana, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = mapping, aes(x = long, y = lat, color = CTDSAL_PSS78)) +  
  theme_minimal()

ggplot(louisiana, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = mapping, aes(x = long, y = lat, color = station)) +  
  theme_minimal()  
  
ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_point(data = mapping, aes(x = long, y = lat, color = CTDSAL_PSS78)) +  
  theme_minimal()

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_text(data = mapping, aes(x = long, y = lat, label = station)) +  
  theme_minimal()

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_text(data = mapping, aes(x = long, y = lat, label = station), size = 3) +  
  coord_fixed(xlim = c(-90.0, -89.25), ylim = c(28.5, 29.25))+
  theme_minimal()

ggplot(mouth, aes(x = long, y = lat)) +
  geom_path() +
  geom_path(data = mapping, aes(x = long, y = lat, color = CTDSAL_PSS78)) +  
  coord_fixed(xlim = c(-90.0, -89.25), ylim = c(28.5, 29.25))+
  theme_minimal()


```



# Towards join with GO data

```{r}

GOfiles <- dir(here("MSR_GO_data/"), "*.txt") # get file names

GOdata <- GOfiles %>% map_dfr(~ read_tsv(here("MSR_GO_data/", .)))

```

```{r}

# combine date and time

```



